export const mockQuotes = [
    {
      id: 1,
      name: 'Quote 1',
      expiryDate: '2023-12-31',
      status: "valid" as "valid",
      totalAmount: 1000,
      files: [],
      tables: [],
    },
    {
      id: 2,
      name: 'Quote 2',
      expiryDate: '2024-06-30',
      status: "valid" as "valid",
      totalAmount: 1500,
      files: [],
      tables: [],
    },
    {
      id: 3,
      name: 'Quote 3',
      expiryDate: '2021-03-10',
      status: "valid" as "valid",
      totalAmount: 5000,
      files: [],
      tables: [],
    },
    {
      id: 4,
      name: 'Quote 4',
      expiryDate: '2022-09-20',
      status: "valid" as "valid",
      totalAmount: 400,
      files: [],
      tables: [],
    },
    {
      id: 5,
      name: 'Quote 5',
      expiryDate: '2022-09-20',
      status: "valid" as "valid",
      totalAmount: 400,
      files: [],
      tables: [],
    },
    {
      id: 6,
      name: 'Quote 6',
      expiryDate: '2022-09-20',
      status: "valid" as "valid",
      totalAmount: 400,
      files: [],
      tables: [],
    },
    // Add more mock quotes here
  ];